format = """
$time\
$line_break\
$status\
${custom.incognito}\
$shlvl\
$jobs\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

[directory]
truncation_length = 6
truncate_to_repo = false
truncation_symbol = ".../"

[shlvl]
disabled = false

[status]
disabled = false

[time]
disabled = false
time_format = "%Y/%m/%d %a %T"
format = "[\\[ $time \\]]($style)"

[character]
vicmd_symbol = "NORMAL [â®](bold green)"

[custom.incognito]
when = "[[ -v ATUIN_INCOGNITO ]]"
symbol = "ğŸ™ˆ"
