#
# Base Format
#
format = """
$time\
$line_break\
$status\
$all\
$line_break\
${custom.incognito}\
$jobs\
$battery\
$os\
$container\
$shell\
$character"""

#
# Custom Settings
#
[gcloud]
disabled = true

[directory]
truncation_length = 6
truncate_to_repo = false
truncation_symbol = ".../"

[shlvl]
disabled = false

[status]
disabled = false

[time]
disabled = false
time_format = "%Y/%m/%d %a %T"
format = "[\\[ $time \\]]($style)"

[character]
vicmd_symbol = "NORMAL [â®](bold green)"

[custom.incognito]
when = "[[ -v ATUIN_INCOGNITO ]]"
symbol = "ğŸ™ˆ"
style = "bold purple"
